#!/bin/sh -e

# Use braces to load the entire script in to memory
{
    echo ** Move to repo
    cd $RUNNER_WORKSPACE/JUCE
    pwd

    git config --global user.email "$GH_NAME"
    git config --global user.name "$GH_EMAIL"

    echo ** Updating tracktion/JUCE from juce-framework/JUCE

    git checkout develop

    echo ** Setup remote
    git remote -v
    git remote add upstream https://github.com/juce-framework/JUCE.git                            
    git remote -v

    echo ** Fetch remote
    git fetch upstream

    echo ** Update develop
    git merge upstream/develop
    git push

    echo ** Update tracktion/develop
    git checkout tracktion/develop
    git merge develop
    git push
}